### ISSUE TITLE
store module

### ISSUE THREAD

**Issue by amirhnajafiz** [linuxfestival/LinuxFest-AdminPanel#43]
Right now we are using ```Vuex``` for store. It's good to use ```Pinia``` which gives us more
readability and maintenance in future updates.

Also be sure to use the ```Pinia``` best practice to make store modules separated.
Visit [pinia login example](https://github.com/cornflourblue/vue-3-pinia-registration-login-example) for best practice.

**Comment by haditabatabaei** [comment]
بچه ها اینو ببینید:

https://github.com/linuxfestival/LinuxFest-Website-Frontend/tree/refactor/refactor-to-vue3

برنچ refactor/refactor-to-vue3 رو برای سایت اصلی خواستید می تونید ادامه بدید (ناقصه).

vite + pinia + vue3 هست.

پیشنهادم اینه بیشتر روی سایت اصلی وقت بذارید تا پنل ادمینش.

کمکی یا چیزی بود حتما بهم اطلاع بدید در خدمتم.

**Comment by amirhnajafiz** [comment]
@mr-amirfazel jan
